[package]
edition = "2024"
name = "mqtt_sht31"
rust-version = "1.91.1"
version = "0.1.0"

[[bin]]
name = "mqtt_sht31"
path = "./src/bin/main.rs"

[dependencies]
critical-section = "1.2.0"
embassy-executor = { version = "0.9.1", features = ["log"] }
embassy-futures = { version = "0.1.2", features = ["log"] }
embassy-net = { version = "0.7.1", features = [
  "dhcpv4",
  "log",
  # "medium-ethernet",
  "tcp",
  # "udp",
] }
embassy-time = { version = "0.5.0", features = ["log"] }
embassy-sync = { version = "0.7.2", features = ["log"] }
embedded-hal-async = "1.0.0"
esp-bootloader-esp-idf = { version = "0.4.0", features = ["esp32c3", "log-04"] }
esp-backtrace = { version = "0.18.1", features = [
  "esp32c3",
  "panic-handler",
  "println",
] }
esp-alloc = "0.9.0"
esp-hal = { version = "1.0.0", features = ["esp32c3", "log-04", "unstable"] }
esp-println = { version = "0.16.1", features = ["esp32c3", "log-04"] }
esp-radio = { version = "0.17.0", features = [
  "esp-alloc",
  "esp32c3",
  "log-04",
  "smoltcp",
  "unstable",
  "wifi",
] }
esp-rtos = { version = "0.2.0", features = [
  "embassy",
  "esp-alloc",
  "esp-radio",
  "esp32c3",
  "log-04",
] }
esp-wifi-sys = { version = "0.8.1", default-features = false, features = [
  "esp32c3",
] }
log = "0.4.27"
heapless = "0.9.2"
mountain-mqtt = { path = "../mountain-mqtt/mountain-mqtt/", default-features = false, features = [
  "embedded-hal-async",
  "embedded-io-async",
] }
mountain-mqtt-embassy = { path = "../mountain-mqtt/mountain-mqtt-embassy/", default-features = false, features = [
  "log",
] }
serde = { version = "1.0", default-features = false, features = [
  "alloc",
  "derive",
] }
serde-json-core = { version = "0.6", default-features = false, features = [
  "heapless",
] }
smoltcp = { version = "0.12.0", default-features = false, features = [
  "log",
  # "medium-ethernet",
  "medium-ip",
  "multicast",
  "proto-dhcpv4",
  "proto-dns",
  "proto-ipv4",
  "socket-dns",
  # "socket-icmp",
  # "socket-raw",
  "socket-tcp",
  # "socket-udp",
] }
sht31 = "0.3.2"
static_cell = "2.1.1"

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
